version: '3.6'

volumes:
  yarn_cache:

services:
  homepage:
    image: knitpk/homepage:latest
    build:
      context: .
      cache_from:
        - knitpk/homepage:latest
    command: ['/bin/sh', '-c', 'yarn install && yarn dev']
    environment:
      - NODE_ENV=development
      - API_URL=https://knit-test-api.tk
      # - API_URL=https://d15e2ckuuchn46.cloudfront.net
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - yarn_cache:/root/.yarn-cache
