version: '3.6'

volumes:
  yarn_cache:

services:
  homepage:
    image: knitpk/homepage:latest
    build:
      context: .
      cache_from:
        - knitpk/homepage:latest
      args:
        - NODE_ENV=development
    command: ['dev']
    environment:
      - API_URL=https://knit-test-api.tk # stage env: https://d15e2ckuuchn46.cloudfront.net
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - yarn_cache:/root/.yarn-cache
