// List mutations
export const ARTICLE_LIST_RETRIEVED_SUCCESS = 'ARTICLE_LIST_RETRIEVED_SUCCESS'
export const ARTICLE_LIST_UPDATE_PAGES_MAP = 'ARTICLE_LIST_UPDATE_PAGES_MAP'
export const ARTICLE_LIST_RETRIEVED_ERROR = 'ARTICLE_LIST_RETRIEVED_ERROR'
export const ARTICLE_LIST_STATUS = 'ARTICLE_LIST_STATUS'

// Item mutations
export const ARTICLE_LIST_ITEM_RETRIEVED_SUCCESS = 'ARTICLE_LIST_ITEM_RETRIEVED_SUCCESS'
export const ARTICLE_LIST_ITEM_RETRIEVED_ERROR = 'ARTICLE_LIST_ITEM_RETRIEVED_ERROR'
export const ARTICLE_LIST_ITEM_STATUS = 'ARTICLE_LIST_ITEM_STATUS'
