// Create types
export const ARTICLE_CREATE_ERROR = 'ARTICLE_CREATE_ERROR'
export const ARTICLE_CREATE_LOADING = 'ARTICLE_CREATE_LOADING'
export const ARTICLE_CREATE_SUCCESS = 'ARTICLE_CREATE_SUCCESS'
export const ARTICLE_CREATE_VIOLATIONS = 'ARTICLE_CREATE_VIOLATIONS'
export const ARTICLE_CREATE_RESET = 'ARTICLE_CREATE_RESET'

// Show types
export const ARTICLE_SHOW_ERROR = 'ARTICLE_SHOW_ERROR'
export const ARTICLE_SHOW_LOADING = 'ARTICLE_SHOW_LOADING'
export const ARTICLE_SHOW_RETRIEVED_SUCCESS = 'ARTICLE_SHOW_RETRIEVED_SUCCESS'
export const ARTICLE_SHOW_RESET = 'ARTICLE_SHOW_RESET'

// Update types
export const ARTICLE_UPDATE_RESET = 'ARTICLE_UPDATE_RESET'
export const ARTICLE_UPDATE_UPDATE_ERROR = 'ARTICLE_UPDATE_UPDATE_ERROR'
export const ARTICLE_UPDATE_UPDATE_LOADING = 'ARTICLE_UPDATE_UPDATE_LOADING'
export const ARTICLE_UPDATE_UPDATE_SUCCESS = 'ARTICLE_UPDATE_UPDATE_SUCCESS'
export const ARTICLE_UPDATE_RETRIEVE_ERROR = 'ARTICLE_UPDATE_RETRIEVE_ERROR'
export const ARTICLE_UPDATE_RETRIEVE_LOADING = 'ARTICLE_UPDATE_RETRIEVE_LOADING'
export const ARTICLE_UPDATE_RETRIEVE_SUCCESS = 'ARTICLE_UPDATE_RETRIEVE_SUCCESS'
export const ARTICLE_UPDATE_UPDATE_VIOLATIONS = 'ARTICLE_UPDATE_UPDATE_VIOLATIONS'

// Delete types
export const ARTICLE_DELETE_ERROR = 'ARTICLE_DELETE_ERROR'
export const ARTICLE_DELETE_LOADING = 'ARTICLE_DELETE_LOADING'
export const ARTICLE_DELETE_SUCCESS = 'ARTICLE_DELETE_SUCCESS'
export const ARTICLE_DELETE_RESET = 'ARTICLE_DELETE_RESET'

// List types
export const ARTICLE_LIST_ERROR = 'ARTICLE_LIST_ERROR'
export const ARTICLE_LIST_LOADING = 'ARTICLE_LIST_LOADING'
export const ARTICLE_LIST_RESET = 'ARTICLE_LIST_RESET'
export const ARTICLE_LIST_VIEW = 'ARTICLE_LIST_VIEW'
export const ARTICLE_LIST_SUCCESS = 'ARTICLE_LIST_SUCCESS'
