// Show types
export const ARTICLE_SHOW_ERROR = 'ARTICLE_SHOW_ERROR'
export const ARTICLE_SHOW_LOADING = 'ARTICLE_SHOW_LOADING'
export const ARTICLE_SHOW_RETRIEVED_SUCCESS = 'ARTICLE_SHOW_RETRIEVED_SUCCESS'
export const ARTICLE_SHOW_RESET = 'ARTICLE_SHOW_RESET'

// List types
export const ARTICLE_LIST_ERROR = 'ARTICLE_LIST_ERROR'
export const ARTICLE_LIST_LOADING = 'ARTICLE_LIST_LOADING'
export const ARTICLE_LIST_RESET = 'ARTICLE_LIST_RESET'
export const ARTICLE_LIST_VIEW = 'ARTICLE_LIST_VIEW'
export const ARTICLE_LIST_SUCCESS = 'ARTICLE_LIST_SUCCESS'
